minimum_pre_commit_version: "3.7.0"
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict

  # Use a local docformatter hook to avoid parsing
  # upstream manifests that may require newer pre-commit features.
  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        entry: docformatter
        language: python
        types: [python]
        additional_dependencies:
          - docformatter==1.7.5
        args:
          - --in-place
          - --wrap-summaries=88
          - --wrap-descriptions=88
          - --pre-summary-newline

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ["--show-error-codes", "--config-file=mypy.ini"]
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-setuptools
        exclude: ^(tests/|scripts/|examples/|test_.*\.py)$
