name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"
        
    - name: Run code formatting check
      run: |
        python -m black --check .
        
    - name: Run linting
      run: |
        python -m ruff check .
        
    - name: Run tests
      run: |
        python -m pytest -v
        
    - name: Verify CLI functionality
      run: |
        autorepro --help
        autorepro --version