name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: UTC
      LC_ALL: C.UTF-8
      PYTHONHASHSEED: "0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files

    - name: Run code formatting check
      run: |
        python -m black --check .

    - name: Run linting
      run: |
        python -m ruff check .

    - name: Run tests
      run: |
        python -m pytest -v

    - name: Golden drift check
      run: |
        python scripts/regold.py --write
        git diff --exit-code

    - name: Verify CLI functionality
      run: |
        autorepro --help
        autorepro --version

    - name: Build report artifact
      continue-on-error: true
      run: |
        autorepro report --desc "CI repro bundle" --exec --timeout 60 --out autorepro_report.zip

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: autorepro-report
        path: autorepro_report.zip
        if-no-files-found: ignore
