name: pre-commit

on:
  pull_request: {}
  push:
    branches: ["main"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pre-commit
        run: python -m pip install --upgrade pip && pip install pre-commit
      - name: Pre-commit clean
        run: pre-commit clean
      - uses: pre-commit/action@v3.0.1
